// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: collector.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------------------
// Handshake
// ---------------------------------------------------------------------
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"` // stable UUID of this collector instance
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`          // tenant slug (matches Django tenant)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                            // collector binary version (semver)
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                          // OS hostname for ops visibility
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                  // ["snmp","ssh","fortigate","mikrotik"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *RegisterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Config        *CollectorConfig       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *CollectorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type CollectorConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MetricBatchSize    int32                  `protobuf:"varint,1,opt,name=metric_batch_size,json=metricBatchSize,proto3" json:"metric_batch_size,omitempty"`          // flush after N metrics
	MetricFlushSeconds int32                  `protobuf:"varint,2,opt,name=metric_flush_seconds,json=metricFlushSeconds,proto3" json:"metric_flush_seconds,omitempty"` // ...or N seconds, whichever first
	HeartbeatSeconds   int32                  `protobuf:"varint,3,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`         // health report cadence
	Adapters           []*AdapterConfig       `protobuf:"bytes,4,rep,name=adapters,proto3" json:"adapters,omitempty"`
	// Per-host tool jobs the operator scheduled in the UI. Each entry tells
	// the agent: "run THIS tool against THAT host every N seconds". Distinct
	// from `adapters` (which are long-lived continuous integrations);
	// jobs are ticker-driven invocations of one Tool executor with
	// resolved credentials inlined into args.
	ScheduledJobs []*ScheduledJob `protobuf:"bytes,5,rep,name=scheduled_jobs,json=scheduledJobs,proto3" json:"scheduled_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorConfig) Reset() {
	*x = CollectorConfig{}
	mi := &file_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorConfig) ProtoMessage() {}

func (x *CollectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorConfig.ProtoReflect.Descriptor instead.
func (*CollectorConfig) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{2}
}

func (x *CollectorConfig) GetMetricBatchSize() int32 {
	if x != nil {
		return x.MetricBatchSize
	}
	return 0
}

func (x *CollectorConfig) GetMetricFlushSeconds() int32 {
	if x != nil {
		return x.MetricFlushSeconds
	}
	return 0
}

func (x *CollectorConfig) GetHeartbeatSeconds() int32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *CollectorConfig) GetAdapters() []*AdapterConfig {
	if x != nil {
		return x.Adapters
	}
	return nil
}

func (x *CollectorConfig) GetScheduledJobs() []*ScheduledJob {
	if x != nil {
		return x.ScheduledJobs
	}
	return nil
}

type AdapterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`     // adapter kind (continuous integration)
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // adapter-specific JSON (URL, intervals)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterConfig) Reset() {
	*x = AdapterConfig{}
	mi := &file_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterConfig) ProtoMessage() {}

func (x *AdapterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterConfig.ProtoReflect.Descriptor instead.
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterConfig) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// One operator-scheduled tool invocation against a managed host. The agent
// keeps a ticker per job and fires the tool with `args` (which already has
// the resolved credential merged in by the server — agent does not look up
// vault entries itself). Result of each invocation is converted to one or
// more Metrics by the per-tool result-to-metric mapping in the agent.
type ScheduledJob struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                // stable id (Django pk) for log correlation
	Tool            string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`                                               // executor name ("snmp.get","ssh.ping","icmp.ping",...)
	Args            *structpb.Struct       `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`                                               // tool-specific args, with secrets merged in
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // tick cadence; <=0 means "run once at startup"
	HostId          string                 `protobuf:"bytes,5,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                             // canonical host identity for Metric.host_id
	Enabled         bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                                        // false = ignored; lets operator pause without delete
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduledJob) Reset() {
	*x = ScheduledJob{}
	mi := &file_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledJob) ProtoMessage() {}

func (x *ScheduledJob) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledJob.ProtoReflect.Descriptor instead.
func (*ScheduledJob) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduledJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScheduledJob) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ScheduledJob) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ScheduledJob) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ScheduledJob) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ScheduledJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ---------------------------------------------------------------------
// Metric stream
// ---------------------------------------------------------------------
type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	BatchSeq      int64                  `protobuf:"varint,2,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"` // monotonic per-collector, used for ack correlation
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{5}
}

func (x *MetricBatch) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *MetricBatch) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *MetricBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	InterfaceName string                 `protobuf:"bytes,5,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // optional (interface metrics)
	PeerId        string                 `protobuf:"bytes,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                      // optional (BGP/OSPF/etc neighbor)
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"` // "snmp" | "syslog" | ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{6}
}

func (x *Metric) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Metric) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Metric) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Metric) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Metric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metric) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MetricAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSeq      int64                  `protobuf:"varint,1,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // empty on success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricAck) Reset() {
	*x = MetricAck{}
	mi := &file_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricAck) ProtoMessage() {}

func (x *MetricAck) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricAck.ProtoReflect.Descriptor instead.
func (*MetricAck) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{7}
}

func (x *MetricAck) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *MetricAck) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *MetricAck) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *MetricAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---------------------------------------------------------------------
// Event stream (state changes)
// ---------------------------------------------------------------------
type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	BatchSeq      int64                  `protobuf:"varint,2,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_collector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{8}
}

func (x *EventBatch) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *EventBatch) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "interface_down" | "bgp_peer_lost" | ...
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                    // "info" | "warning" | "critical"
	Details       *structpb.Struct       `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_collector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSeq      int64                  `protobuf:"varint,1,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`
	Accepted      int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_collector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{10}
}

func (x *EventAck) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *EventAck) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *EventAck) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *EventAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---------------------------------------------------------------------
// Reverse tool channel (server → collector → device)
// Used by IA causal layer to probe customer environment on demand.
// ---------------------------------------------------------------------
type ToolCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // server-generated UUID; echoed back
	Tool           string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`                            // "ssh.exec" | "snmp.get" | ...
	Args           *structpb.Struct       `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`                            // tool-specific payload
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCommand) Reset() {
	*x = ToolCommand{}
	mi := &file_collector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCommand) ProtoMessage() {}

func (x *ToolCommand) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCommand.ProtoReflect.Descriptor instead.
func (*ToolCommand) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ToolCommand) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCommand) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_collector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{12}
}

func (x *ToolResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ToolResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ToolResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ---------------------------------------------------------------------
// Health beacon
// ---------------------------------------------------------------------
type HealthReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CollectorId      string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	LagSeconds       float64                `protobuf:"fixed64,3,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`      // how far behind real-time the pipeline is
	DropsPerMin      float64                `protobuf:"fixed64,4,opt,name=drops_per_min,json=dropsPerMin,proto3" json:"drops_per_min,omitempty"` // metrics/events dropped due to backpressure
	UptimeSeconds    float64                `protobuf:"fixed64,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MetricsSentTotal int64                  `protobuf:"varint,6,opt,name=metrics_sent_total,json=metricsSentTotal,proto3" json:"metrics_sent_total,omitempty"`
	EventsSentTotal  int64                  `protobuf:"varint,7,opt,name=events_sent_total,json=eventsSentTotal,proto3" json:"events_sent_total,omitempty"`
	Custom           map[string]float64     `protobuf:"bytes,8,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // adapter-specific gauges
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_collector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{13}
}

func (x *HealthReport) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *HealthReport) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HealthReport) GetLagSeconds() float64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

func (x *HealthReport) GetDropsPerMin() float64 {
	if x != nil {
		return x.DropsPerMin
	}
	return 0
}

func (x *HealthReport) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthReport) GetMetricsSentTotal() int64 {
	if x != nil {
		return x.MetricsSentTotal
	}
	return 0
}

func (x *HealthReport) GetEventsSentTotal() int64 {
	if x != nil {
		return x.EventsSentTotal
	}
	return 0
}

func (x *HealthReport) GetCustom() map[string]float64 {
	if x != nil {
		return x.Custom
	}
	return nil
}

type HealthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAck) Reset() {
	*x = HealthAck{}
	mi := &file_collector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAck) ProtoMessage() {}

func (x *HealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAck.ProtoReflect.Descriptor instead.
func (*HealthAck) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{14}
}

func (x *HealthAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_collector_proto protoreflect.FileDescriptor

const file_collector_proto_rawDesc = "" +
	"\n" +
	"\x0fcollector.proto\x12\x15ispwatch.collector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xab\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xb0\x01\n" +
	"\x10RegisterResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12>\n" +
	"\x06config\x18\x02 \x01(\v2&.ispwatch.collector.v1.CollectorConfigR\x06config\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"\xaa\x02\n" +
	"\x0fCollectorConfig\x12*\n" +
	"\x11metric_batch_size\x18\x01 \x01(\x05R\x0fmetricBatchSize\x120\n" +
	"\x14metric_flush_seconds\x18\x02 \x01(\x05R\x12metricFlushSeconds\x12+\n" +
	"\x11heartbeat_seconds\x18\x03 \x01(\x05R\x10heartbeatSeconds\x12@\n" +
	"\badapters\x18\x04 \x03(\v2$.ispwatch.collector.v1.AdapterConfigR\badapters\x12J\n" +
	"\x0escheduled_jobs\x18\x05 \x03(\v2#.ispwatch.collector.v1.ScheduledJobR\rscheduledJobs\"T\n" +
	"\rAdapterConfig\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xc4\x01\n" +
	"\fScheduledJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12\x17\n" +
	"\ahost_id\x18\x05 \x01(\tR\x06hostId\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"\x86\x01\n" +
	"\vMetricBatch\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x1b\n" +
	"\tbatch_seq\x18\x02 \x01(\x03R\bbatchSeq\x127\n" +
	"\ametrics\x18\x03 \x03(\v2\x1d.ispwatch.collector.v1.MetricR\ametrics\"\xd6\x02\n" +
	"\x06Metric\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12%\n" +
	"\x0einterface_name\x18\x05 \x01(\tR\rinterfaceName\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\tR\x06peerId\x12;\n" +
	"\x04tags\x18\a \x03(\v2'.ispwatch.collector.v1.Metric.TagsEntryR\x04tags\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\tMetricAck\x12\x1b\n" +
	"\tbatch_seq\x18\x01 \x01(\x03R\bbatchSeq\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x05R\brejected\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x82\x01\n" +
	"\n" +
	"EventBatch\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12\x1b\n" +
	"\tbatch_seq\x18\x02 \x01(\x03R\bbatchSeq\x124\n" +
	"\x06events\x18\x03 \x03(\v2\x1c.ispwatch.collector.v1.EventR\x06events\"\xbe\x01\n" +
	"\x05Event\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x121\n" +
	"\adetails\x18\x05 \x01(\v2\x17.google.protobuf.StructR\adetails\"u\n" +
	"\bEventAck\x12\x1b\n" +
	"\tbatch_seq\x18\x01 \x01(\x03R\bbatchSeq\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x05R\brejected\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x96\x01\n" +
	"\vToolCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xa3\x01\n" +
	"\n" +
	"ToolResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\xab\x03\n" +
	"\fHealthReport\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1f\n" +
	"\vlag_seconds\x18\x03 \x01(\x01R\n" +
	"lagSeconds\x12\"\n" +
	"\rdrops_per_min\x18\x04 \x01(\x01R\vdropsPerMin\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x01R\ruptimeSeconds\x12,\n" +
	"\x12metrics_sent_total\x18\x06 \x01(\x03R\x10metricsSentTotal\x12*\n" +
	"\x11events_sent_total\x18\a \x01(\x03R\x0feventsSentTotal\x12G\n" +
	"\x06custom\x18\b \x03(\v2/.ispwatch.collector.v1.HealthReport.CustomEntryR\x06custom\x1a9\n" +
	"\vCustomEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x1b\n" +
	"\tHealthAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd3\x03\n" +
	"\x10CollectorService\x12[\n" +
	"\bRegister\x12&.ispwatch.collector.v1.RegisterRequest\x1a'.ispwatch.collector.v1.RegisterResponse\x12Y\n" +
	"\rStreamMetrics\x12\".ispwatch.collector.v1.MetricBatch\x1a .ispwatch.collector.v1.MetricAck(\x010\x01\x12V\n" +
	"\fStreamEvents\x12!.ispwatch.collector.v1.EventBatch\x1a\x1f.ispwatch.collector.v1.EventAck(\x010\x01\x12X\n" +
	"\vToolChannel\x12!.ispwatch.collector.v1.ToolResult\x1a\".ispwatch.collector.v1.ToolCommand(\x010\x01\x12U\n" +
	"\fReportHealth\x12#.ispwatch.collector.v1.HealthReport\x1a .ispwatch.collector.v1.HealthAckBV\n" +
	"\x1esystem.monitoring.collector.v1P\x01Z2github.com/ispwatch/collector/proto/v1;collectorv1b\x06proto3"

var (
	file_collector_proto_rawDescOnce sync.Once
	file_collector_proto_rawDescData []byte
)

func file_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)))
	})
	return file_collector_proto_rawDescData
}

var file_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_collector_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: ispwatch.collector.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: ispwatch.collector.v1.RegisterResponse
	(*CollectorConfig)(nil),       // 2: ispwatch.collector.v1.CollectorConfig
	(*AdapterConfig)(nil),         // 3: ispwatch.collector.v1.AdapterConfig
	(*ScheduledJob)(nil),          // 4: ispwatch.collector.v1.ScheduledJob
	(*MetricBatch)(nil),           // 5: ispwatch.collector.v1.MetricBatch
	(*Metric)(nil),                // 6: ispwatch.collector.v1.Metric
	(*MetricAck)(nil),             // 7: ispwatch.collector.v1.MetricAck
	(*EventBatch)(nil),            // 8: ispwatch.collector.v1.EventBatch
	(*Event)(nil),                 // 9: ispwatch.collector.v1.Event
	(*EventAck)(nil),              // 10: ispwatch.collector.v1.EventAck
	(*ToolCommand)(nil),           // 11: ispwatch.collector.v1.ToolCommand
	(*ToolResult)(nil),            // 12: ispwatch.collector.v1.ToolResult
	(*HealthReport)(nil),          // 13: ispwatch.collector.v1.HealthReport
	(*HealthAck)(nil),             // 14: ispwatch.collector.v1.HealthAck
	nil,                           // 15: ispwatch.collector.v1.Metric.TagsEntry
	nil,                           // 16: ispwatch.collector.v1.HealthReport.CustomEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
}
var file_collector_proto_depIdxs = []int32{
	2,  // 0: ispwatch.collector.v1.RegisterResponse.config:type_name -> ispwatch.collector.v1.CollectorConfig
	17, // 1: ispwatch.collector.v1.RegisterResponse.issued_at:type_name -> google.protobuf.Timestamp
	3,  // 2: ispwatch.collector.v1.CollectorConfig.adapters:type_name -> ispwatch.collector.v1.AdapterConfig
	4,  // 3: ispwatch.collector.v1.CollectorConfig.scheduled_jobs:type_name -> ispwatch.collector.v1.ScheduledJob
	18, // 4: ispwatch.collector.v1.AdapterConfig.params:type_name -> google.protobuf.Struct
	18, // 5: ispwatch.collector.v1.ScheduledJob.args:type_name -> google.protobuf.Struct
	6,  // 6: ispwatch.collector.v1.MetricBatch.metrics:type_name -> ispwatch.collector.v1.Metric
	17, // 7: ispwatch.collector.v1.Metric.time:type_name -> google.protobuf.Timestamp
	15, // 8: ispwatch.collector.v1.Metric.tags:type_name -> ispwatch.collector.v1.Metric.TagsEntry
	9,  // 9: ispwatch.collector.v1.EventBatch.events:type_name -> ispwatch.collector.v1.Event
	17, // 10: ispwatch.collector.v1.Event.time:type_name -> google.protobuf.Timestamp
	18, // 11: ispwatch.collector.v1.Event.details:type_name -> google.protobuf.Struct
	18, // 12: ispwatch.collector.v1.ToolCommand.args:type_name -> google.protobuf.Struct
	18, // 13: ispwatch.collector.v1.ToolResult.result:type_name -> google.protobuf.Struct
	17, // 14: ispwatch.collector.v1.HealthReport.time:type_name -> google.protobuf.Timestamp
	16, // 15: ispwatch.collector.v1.HealthReport.custom:type_name -> ispwatch.collector.v1.HealthReport.CustomEntry
	0,  // 16: ispwatch.collector.v1.CollectorService.Register:input_type -> ispwatch.collector.v1.RegisterRequest
	5,  // 17: ispwatch.collector.v1.CollectorService.StreamMetrics:input_type -> ispwatch.collector.v1.MetricBatch
	8,  // 18: ispwatch.collector.v1.CollectorService.StreamEvents:input_type -> ispwatch.collector.v1.EventBatch
	12, // 19: ispwatch.collector.v1.CollectorService.ToolChannel:input_type -> ispwatch.collector.v1.ToolResult
	13, // 20: ispwatch.collector.v1.CollectorService.ReportHealth:input_type -> ispwatch.collector.v1.HealthReport
	1,  // 21: ispwatch.collector.v1.CollectorService.Register:output_type -> ispwatch.collector.v1.RegisterResponse
	7,  // 22: ispwatch.collector.v1.CollectorService.StreamMetrics:output_type -> ispwatch.collector.v1.MetricAck
	10, // 23: ispwatch.collector.v1.CollectorService.StreamEvents:output_type -> ispwatch.collector.v1.EventAck
	11, // 24: ispwatch.collector.v1.CollectorService.ToolChannel:output_type -> ispwatch.collector.v1.ToolCommand
	14, // 25: ispwatch.collector.v1.CollectorService.ReportHealth:output_type -> ispwatch.collector.v1.HealthAck
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_collector_proto_init() }
func file_collector_proto_init() {
	if File_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_depIdxs,
		MessageInfos:      file_collector_proto_msgTypes,
	}.Build()
	File_collector_proto = out.File
	file_collector_proto_goTypes = nil
	file_collector_proto_depIdxs = nil
}
