// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: collector.proto

package collectorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_Register_FullMethodName      = "/ispwatch.collector.v1.CollectorService/Register"
	CollectorService_StreamMetrics_FullMethodName = "/ispwatch.collector.v1.CollectorService/StreamMetrics"
	CollectorService_StreamEvents_FullMethodName  = "/ispwatch.collector.v1.CollectorService/StreamEvents"
	CollectorService_ToolChannel_FullMethodName   = "/ispwatch.collector.v1.CollectorService/ToolChannel"
	CollectorService_ReportHealth_FullMethodName  = "/ispwatch.collector.v1.CollectorService/ReportHealth"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =====================================================================
// CollectorService runs on the central IspWatch server.
// Collector daemons connect TO it over mTLS (reverse tunnel pattern —
// collectors behind NAT can be reached from the central control plane
// without inbound firewall rules at the customer side).
//
// Streams are long-lived: the collector opens them at startup and keeps
// them open. Reconnect logic lives in the collector binary (Go).
// =====================================================================
type CollectorServiceClient interface {
	// Handshake. Sent once at startup and after every reconnect.
	// Server returns the runtime config (which adapters to enable, batch
	// sizes, intervals) and a session token used in subsequent streams.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Long-lived metric stream. Collector pushes batches; server acks.
	// Bidirectional so server can backpressure ("slow down") via ack flow.
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricBatch, MetricAck], error)
	// Long-lived event stream (state changes — link down, BGP lost, etc).
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, EventAck], error)
	// Reverse channel for MCP-like tool execution.
	// Collector keeps this stream open; server pushes ToolCommand whenever
	// the IA causal layer needs to probe the customer environment
	// (run an SSH command, poll an SNMP OID, query Zabbix history, etc).
	// Collector executes locally and returns ToolResult.
	ToolChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ToolResult, ToolCommand], error)
	// Periodic health beacon (lag, drops, uptime). Feeds collector_health
	// hypertable in TimescaleDB.
	ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthAck, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, CollectorService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricBatch, MetricAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], CollectorService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricBatch, MetricAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_StreamMetricsClient = grpc.BidiStreamingClient[MetricBatch, MetricAck]

func (c *collectorServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[1], CollectorService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_StreamEventsClient = grpc.BidiStreamingClient[EventBatch, EventAck]

func (c *collectorServiceClient) ToolChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ToolResult, ToolCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[2], CollectorService_ToolChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ToolResult, ToolCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ToolChannelClient = grpc.BidiStreamingClient[ToolResult, ToolCommand]

func (c *collectorServiceClient) ReportHealth(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthAck)
	err := c.cc.Invoke(ctx, CollectorService_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
//
// =====================================================================
// CollectorService runs on the central IspWatch server.
// Collector daemons connect TO it over mTLS (reverse tunnel pattern —
// collectors behind NAT can be reached from the central control plane
// without inbound firewall rules at the customer side).
//
// Streams are long-lived: the collector opens them at startup and keeps
// them open. Reconnect logic lives in the collector binary (Go).
// =====================================================================
type CollectorServiceServer interface {
	// Handshake. Sent once at startup and after every reconnect.
	// Server returns the runtime config (which adapters to enable, batch
	// sizes, intervals) and a session token used in subsequent streams.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Long-lived metric stream. Collector pushes batches; server acks.
	// Bidirectional so server can backpressure ("slow down") via ack flow.
	StreamMetrics(grpc.BidiStreamingServer[MetricBatch, MetricAck]) error
	// Long-lived event stream (state changes — link down, BGP lost, etc).
	StreamEvents(grpc.BidiStreamingServer[EventBatch, EventAck]) error
	// Reverse channel for MCP-like tool execution.
	// Collector keeps this stream open; server pushes ToolCommand whenever
	// the IA causal layer needs to probe the customer environment
	// (run an SSH command, poll an SNMP OID, query Zabbix history, etc).
	// Collector executes locally and returns ToolResult.
	ToolChannel(grpc.BidiStreamingServer[ToolResult, ToolCommand]) error
	// Periodic health beacon (lag, drops, uptime). Feeds collector_health
	// hypertable in TimescaleDB.
	ReportHealth(context.Context, *HealthReport) (*HealthAck, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCollectorServiceServer) StreamMetrics(grpc.BidiStreamingServer[MetricBatch, MetricAck]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedCollectorServiceServer) StreamEvents(grpc.BidiStreamingServer[EventBatch, EventAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedCollectorServiceServer) ToolChannel(grpc.BidiStreamingServer[ToolResult, ToolCommand]) error {
	return status.Error(codes.Unimplemented, "method ToolChannel not implemented")
}
func (UnimplementedCollectorServiceServer) ReportHealth(context.Context, *HealthReport) (*HealthAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).StreamMetrics(&grpc.GenericServerStream[MetricBatch, MetricAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_StreamMetricsServer = grpc.BidiStreamingServer[MetricBatch, MetricAck]

func _CollectorService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).StreamEvents(&grpc.GenericServerStream[EventBatch, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_StreamEventsServer = grpc.BidiStreamingServer[EventBatch, EventAck]

func _CollectorService_ToolChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).ToolChannel(&grpc.GenericServerStream[ToolResult, ToolCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ToolChannelServer = grpc.BidiStreamingServer[ToolResult, ToolCommand]

func _CollectorService_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ReportHealth(ctx, req.(*HealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ispwatch.collector.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CollectorService_Register_Handler,
		},
		{
			MethodName: "ReportHealth",
			Handler:    _CollectorService_ReportHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _CollectorService_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _CollectorService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ToolChannel",
			Handler:       _CollectorService_ToolChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "collector.proto",
}
