apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ispwatch-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ispwatch-agent.labels" . | nindent 4 }}
